apiVersion: v1
kind: Secret
metadata:
  name: event-booking-secrets
  namespace: onlineeventbookingumerkhan
type: Opaque
data:
  MONGO_USER_SERVICE_PASSWORD: cGFzc3dvcmQ= # "password" in Base64
  MONGO_EVENT_SERVICE_PASSWORD: cGFzc3dvcmQ= # "password" in Base64
  MONGO_BOOKING_SERVICE_PASSWORD: cGFzc3dvcmQ= # "password" in Base64
  MONGO_NOTIFICATION_SERVICE_PASSWORD: cGFzc3dvcmQ= # "password" in Base64
