name: Sync GitHub Kanban with Jira

on:
  project_card:
    types: [moved]

jobs:
  sync-to-jira:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Jira Issue
        uses: atlassian/gajira-create@v3
        with:
          project: "CIUK"  # Replace with your actual Jira project key
          issuetype: "Task"  # Change if needed
          summary: "Sync GitHub Kanban card"
          description: "Issue created from GitHub Kanban board"
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_SITE }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
